services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ap2
      POSTGRES_PASSWORD: ap2
      POSTGRES_DB: ap2
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
